// examples/solid/src/app.tsx
import { RegistryProvider, useAtomResource, useAtomSet, useAtomValue } from "@effect/atom-solid";
import { Duration, Effect } from "effect";
import { createEffect, createMemo, Show, Suspense } from "solid-js";
import { Transition } from "solid-transition-group";

import type { CounterActorAtom, CounterAtoms } from "@effect-machine/examples-shared/counter";
import { CounterEvent, makeCounterAtoms } from "@effect-machine/examples-shared/counter";

export interface ComputationCounters {
  readonly count?: (() => void) | undefined;
  readonly label?: (() => void) | undefined;
  readonly status?: (() => void) | undefined;
  readonly canIncrement?: (() => void) | undefined;
}

const Count = (props: { readonly atoms: CounterAtoms; readonly onCompute?: () => void }) => {
  const count = useAtomValue(() => props.atoms.count);
  createEffect(() => {
    count();
    props.onCompute?.();
  });
  return <output aria-label="Count">{count()}</output>;
};

const Label = (props: { readonly atoms: CounterAtoms; readonly onCompute?: () => void }) => {
  const label = useAtomValue(() => props.atoms.label);
  createEffect(() => {
    label();
    props.onCompute?.();
  });
  return <h1>{label()}</h1>;
};

const Controls = (props: {
  readonly atoms: CounterAtoms;
  readonly onCanIncrementCompute?: () => void;
}) => {
  const send = useAtomSet(() => props.atoms.state);
  const [canIncrement] = useAtomResource(() => props.atoms.canIncrement);
  createEffect(() => {
    canIncrement();
    props.onCanIncrementCompute?.();
  });
  return (
    <div>
      <button type="button" disabled={!canIncrement()} onClick={() => send(CounterEvent.Increment)}>
        Increment
      </button>
      <button type="button" onClick={() => send(CounterEvent.Rename({ label: "Renamed" }))}>
        Rename
      </button>
      <button type="button" onClick={() => send(CounterEvent.Finish)}>
        Finish
      </button>
    </div>
  );
};

const exitDuration = Duration.millis(200);

const completeExit = (_element: Element, done: () => void): void => {
  Effect.runFork(Effect.delay(Effect.sync(done), exitDuration));
};

const AnimatedCounter = (props: {
  readonly atoms: CounterAtoms;
  readonly computations?: ComputationCounters | undefined;
}) => {
  const status = useAtomValue(() => props.atoms.status);
  createEffect(() => {
    status();
    props.computations?.status?.();
  });
  return (
    <>
      <output aria-label="Status">{status()}</output>
      <Transition name="counter" onExit={completeExit}>
        <Show when={status() === "Active"}>
          <main data-testid="counter-screen">
            <Label atoms={props.atoms} onCompute={props.computations?.label} />
            <Count atoms={props.atoms} onCompute={props.computations?.count} />
            <Controls
              atoms={props.atoms}
              onCanIncrementCompute={props.computations?.canIncrement}
            />
          </main>
        </Show>
      </Transition>
    </>
  );
};

const SuspendedCounter = (props: {
  readonly actorAtom: CounterActorAtom;
  readonly computations?: ComputationCounters | undefined;
}) => {
  const [actor] = useAtomResource(() => props.actorAtom);
  const atoms = createMemo(() => {
    const value = actor();
    if (value === undefined) return undefined;
    return makeCounterAtoms(value);
  });
  return (
    <Show when={atoms()}>
      {(value) => <AnimatedCounter atoms={value()} computations={props.computations} />}
    </Show>
  );
};

export const App = (props: {
  readonly actorAtom: CounterActorAtom;
  readonly computations?: ComputationCounters | undefined;
}) => (
  <RegistryProvider>
    <Suspense fallback={<p>Starting actor…</p>}>
      <SuspendedCounter actorAtom={props.actorAtom} computations={props.computations} />
    </Suspense>
  </RegistryProvider>
);

// examples/react/src/app.tsx
import { RegistryProvider, useAtomSet, useAtomSuspense, useAtomValue } from "@effect/atom-react";
import { AnimatePresence, motion } from "motion/react";
import { Suspense, useMemo } from "react";

import type { CounterActorAtom, CounterAtoms } from "@effect-machine/examples-shared/counter";
import { CounterEvent, makeCounterAtoms } from "@effect-machine/examples-shared/counter";

export interface RenderCounters {
  readonly count?: (() => void) | undefined;
  readonly label?: (() => void) | undefined;
  readonly status?: (() => void) | undefined;
  readonly canIncrement?: (() => void) | undefined;
}

const Count = (props: { readonly atoms: CounterAtoms; readonly onRender?: () => void }) => {
  props.onRender?.();
  const count = useAtomValue(props.atoms.count);
  return <output aria-label="Count">{count}</output>;
};

const Label = (props: { readonly atoms: CounterAtoms; readonly onRender?: () => void }) => {
  props.onRender?.();
  const label = useAtomValue(props.atoms.label);
  return <h1>{label}</h1>;
};

const Controls = (props: {
  readonly atoms: CounterAtoms;
  readonly onCanIncrementRender?: () => void;
}) => {
  props.onCanIncrementRender?.();
  const send = useAtomSet(props.atoms.state);
  const canIncrement = useAtomSuspense(props.atoms.canIncrement).value;
  return (
    <div>
      <button type="button" disabled={!canIncrement} onClick={() => send(CounterEvent.Increment)}>
        Increment
      </button>
      <button type="button" onClick={() => send(CounterEvent.Rename({ label: "Renamed" }))}>
        Rename
      </button>
      <button type="button" onClick={() => send(CounterEvent.Finish)}>
        Finish
      </button>
    </div>
  );
};

const AnimatedCounter = (props: {
  readonly atoms: CounterAtoms;
  readonly renders?: RenderCounters | undefined;
}) => {
  props.renders?.status?.();
  const status = useAtomValue(props.atoms.status);
  return (
    <>
      <output aria-label="Status">{status}</output>
      <AnimatePresence>
        {status === "Active" && (
          <motion.main
            key="counter"
            data-testid="counter-screen"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.2 }}
          >
            <Label atoms={props.atoms} onRender={props.renders?.label} />
            <Count atoms={props.atoms} onRender={props.renders?.count} />
            <Controls atoms={props.atoms} onCanIncrementRender={props.renders?.canIncrement} />
          </motion.main>
        )}
      </AnimatePresence>
    </>
  );
};

const SuspendedCounter = (props: {
  readonly actorAtom: CounterActorAtom;
  readonly renders?: RenderCounters | undefined;
}) => {
  const actor = useAtomSuspense(props.actorAtom).value;
  const atoms = useMemo(() => makeCounterAtoms(actor), [actor]);
  return <AnimatedCounter atoms={atoms} renders={props.renders} />;
};

export const App = (props: {
  readonly actorAtom: CounterActorAtom;
  readonly renders?: RenderCounters | undefined;
}) => (
  <RegistryProvider>
    <Suspense fallback={<p>Starting actor…</p>}>
      <SuspendedCounter actorAtom={props.actorAtom} renders={props.renders} />
    </Suspense>
  </RegistryProvider>
);
