// examples/solid/src/main.tsx
import { render } from "solid-js/web";

import { makeCounterActorAtom } from "@effect-machine/examples-shared/counter";
import { App } from "./app.js";
import "./styles.css";

const rootElement = document.getElementById("root");

if (rootElement !== null) {
  const dispose = render(() => <App actorAtom={makeCounterActorAtom()} />, rootElement);
  import.meta.hot?.dispose(() => {
    dispose();
  });
}

// examples/react/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import { makeCounterActorAtom } from "@effect-machine/examples-shared/counter";
import { App } from "./app.js";

const rootElement = document.getElementById("root");

if (rootElement !== null) {
  const root = createRoot(rootElement);
  root.render(
    <StrictMode>
      <App actorAtom={makeCounterActorAtom()} />
    </StrictMode>,
  );
  import.meta.hot?.dispose(() => {
    root.unmount();
  });
}
